# 
service: portfolio

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-s3-local
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  s3:
    port: 4568
    directory: /mocks/${env:paumb_img_bucket}
provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
        - s3:ListBucket
      Resource: "*"

  environment:
    pauportfolio: ${env:pauportfolio}
    xisportfolio: ${env:xisportfolio}
    cbdmaravilla: ${env:cbdmaravilla}

functions:
  getImages:
    handler: getImages.handler
    events:
      - http:
          path: images
          method: get
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - apisite
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

  sendMail:
    handler: sendMail.handler
    events:
      - http:
          path: email/send
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - apisite
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

resources:
  - ${file(resources/api-gateway-errors.yml)}