# 
service: portfolio

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "execute-api:Invoke",
        - "execute-api:ManageConnections"
      Resource: "*"

  environment:
    pauportfolio: ${env:pauportfolio}
    xisportfolio: ${env:xisportfolio}
    cbdmaravilla: ${env:cbdmaravilla}

functions:
  sendMail:
    handler: sendMail.handler
    events:
      - http:
          path: email/send
          method: post
          cors:
            origin: '*' # <-- Specify allowed origin
            headers: # <-- Specify allowed headers
              - apisite
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

resources:
  - ${file(resources/api-gateway-errors.yml)}